"""EVM mechanism for x402 payment protocol."""

# Constants
from .constants import (
    AUTHORIZATION_STATE_ABI,
    BALANCE_OF_ABI,
    ERC20_ALLOWANCE_ABI,
    ERC20_APPROVE_ABI,
    DEFAULT_MAX_FEE_PER_GAS,
    DEFAULT_MAX_PRIORITY_FEE_PER_GAS,
    EIP2612_NONCES_ABI,
    EIP2612_PERMIT_TYPES,
    ERC20_APPROVE_GAS_LIMIT,
    DEFAULT_DECIMALS,
    DEFAULT_VALIDITY_PERIOD,
    EIP1271_MAGIC_VALUE,
    ERC6492_MAGIC_VALUE,
    ERR_FAILED_TO_GET_ASSET_INFO,
    ERR_FAILED_TO_GET_NETWORK_CONFIG,
    ERR_FAILED_TO_VERIFY_SIGNATURE,
    ERR_INSUFFICIENT_AMOUNT,
    ERR_INSUFFICIENT_BALANCE,
    ERR_INVALID_SIGNATURE,
    ERR_MISSING_EIP712_DOMAIN,
    ERR_NETWORK_MISMATCH,
    ERR_NONCE_ALREADY_USED,
    ERR_PERMIT2_2612_AMOUNT_MISMATCH,
    ERR_PERMIT2_ALLOWANCE_REQUIRED,
    ERR_PERMIT2_AMOUNT_MISMATCH,
    ERR_PERMIT2_DEADLINE_EXPIRED,
    ERR_PERMIT2_INVALID_AMOUNT,
    ERR_PERMIT2_INVALID_DESTINATION,
    ERR_PERMIT2_INVALID_FACILITATOR,
    ERR_PERMIT2_INVALID_NONCE,
    ERR_PERMIT2_INVALID_OWNER,
    ERR_PERMIT2_INVALID_SIGNATURE,
    ERR_PERMIT2_INVALID_SPENDER,
    ERR_PERMIT2_NOT_YET_VALID,
    ERR_PERMIT2_PAYMENT_TOO_EARLY,
    ERR_PERMIT2_RECIPIENT_MISMATCH,
    ERR_PERMIT2_TOKEN_MISMATCH,
    ERR_EIP2612_EXTENSION_FORMAT,
    ERR_EIP2612_FROM_MISMATCH,
    ERR_EIP2612_ASSET_MISMATCH,
    ERR_EIP2612_SPENDER_NOT_PERMIT2,
    ERR_EIP2612_DEADLINE_EXPIRED,
    ERR_ERC20_APPROVAL_EXTENSION_FORMAT,
    ERR_ERC20_APPROVAL_FROM_MISMATCH,
    ERR_ERC20_APPROVAL_ASSET_MISMATCH,
    ERR_ERC20_APPROVAL_SPENDER_NOT_PERMIT2,
    ERR_ERC20_APPROVAL_TX_FAILED,
    ERR_RECIPIENT_MISMATCH,
    ERR_SMART_WALLET_DEPLOYMENT_FAILED,
    ERR_TRANSACTION_FAILED,
    ERR_UNDEPLOYED_SMART_WALLET,
    ERR_UNSUPPORTED_SCHEME,
    ERR_VALID_AFTER_FUTURE,
    ERR_VALID_BEFORE_EXPIRED,
    IS_VALID_SIGNATURE_ABI,
    NETWORK_CONFIGS,
    PERMIT2_ADDRESSES,
    PERMIT2_ADDRESS,
    PERMIT2_WITNESS_TYPES,
    SCHEME_EXACT,
    TRANSFER_WITH_AUTHORIZATION_BYTES_ABI,
    TRANSFER_WITH_AUTHORIZATION_VRS_ABI,
    TX_STATUS_FAILED,
    TX_STATUS_SUCCESS,
    X402_EXACT_PERMIT2_PROXY_ADDRESSES,
    X402_EXACT_PERMIT2_PROXY_ADDRESS,
    get_permit2_address,
    get_x402_exact_permit2_proxy_address,
    x402ExactPermit2ProxyABI,
    AssetInfo,
    NetworkConfig,
)

# EIP-712
from .eip712 import (
    build_typed_data_for_signing,
    hash_domain,
    hash_eip3009_authorization,
    hash_struct,
    hash_typed_data,
)

# ERC-6492
from .erc6492 import (
    has_deployment_info,
    is_eoa_signature,
    is_erc6492_signature,
    parse_erc6492_signature,
)

# Signer protocols
from .signer import ClientEvmSigner, FacilitatorEvmSigner

# Signer implementations
from .signers import EthAccountSigner, FacilitatorWeb3Signer

# Types
from .types import (
    AUTHORIZATION_TYPES,
    DOMAIN_TYPES,
    ERC6492SignatureData,
    ExactEIP3009Authorization,
    ExactEIP3009Payload,
    ExactPermit2Payload,
    ExactEvmPayloadV1,
    ExactEvmPayloadV2,
    Permit2Authorization,
    Permit2Witness,
    TransactionReceipt,
    TypedDataDomain,
    TypedDataField,
    is_permit2_payload,
)

# Utilities
from .utils import (
    bytes_to_hex,
    create_nonce,
    create_validity_window,
    format_amount,
    get_asset_info,
    get_evm_chain_id,
    get_network_config,
    hex_to_bytes,
    is_valid_address,
    is_valid_network,
    normalize_address,
    parse_amount,
    parse_money_to_decimal,
)

# V1 legacy constants (re-exported for backward compatibility)
from .v1.constants import (
    V1_NETWORK_CHAIN_IDS,
    V1_NETWORKS,
)

# Verification
from .verify import (
    verify_eip1271_signature,
    verify_eoa_signature,
    verify_universal_signature,
)

__all__ = [
    # Constants
    "SCHEME_EXACT",
    "DEFAULT_DECIMALS",
    "DEFAULT_VALIDITY_PERIOD",
    "TX_STATUS_SUCCESS",
    "TX_STATUS_FAILED",
    "ERC6492_MAGIC_VALUE",
    "EIP1271_MAGIC_VALUE",
    "NETWORK_CONFIGS",
    "V1_NETWORKS",
    "V1_NETWORK_CHAIN_IDS",
    "ERR_INVALID_SIGNATURE",
    "ERR_UNDEPLOYED_SMART_WALLET",
    "ERR_SMART_WALLET_DEPLOYMENT_FAILED",
    "ERR_RECIPIENT_MISMATCH",
    "ERR_INSUFFICIENT_AMOUNT",
    "ERR_VALID_BEFORE_EXPIRED",
    "ERR_VALID_AFTER_FUTURE",
    "ERR_NONCE_ALREADY_USED",
    "ERR_INSUFFICIENT_BALANCE",
    "ERR_MISSING_EIP712_DOMAIN",
    "ERR_NETWORK_MISMATCH",
    "ERR_UNSUPPORTED_SCHEME",
    "ERR_TRANSACTION_FAILED",
    "ERR_PERMIT2_INVALID_SPENDER",
    "ERR_PERMIT2_RECIPIENT_MISMATCH",
    "ERR_PERMIT2_INVALID_FACILITATOR",
    "ERR_PERMIT2_DEADLINE_EXPIRED",
    "ERR_PERMIT2_NOT_YET_VALID",
    "ERR_PERMIT2_AMOUNT_MISMATCH",
    "ERR_PERMIT2_TOKEN_MISMATCH",
    "ERR_PERMIT2_INVALID_SIGNATURE",
    "ERR_PERMIT2_ALLOWANCE_REQUIRED",
    "ERR_PERMIT2_INVALID_AMOUNT",
    "ERR_PERMIT2_INVALID_DESTINATION",
    "ERR_PERMIT2_INVALID_OWNER",
    "ERR_PERMIT2_PAYMENT_TOO_EARLY",
    "ERR_PERMIT2_INVALID_NONCE",
    "ERR_PERMIT2_2612_AMOUNT_MISMATCH",
    "ERR_EIP2612_EXTENSION_FORMAT",
    "ERR_EIP2612_FROM_MISMATCH",
    "ERR_EIP2612_ASSET_MISMATCH",
    "ERR_EIP2612_SPENDER_NOT_PERMIT2",
    "ERR_EIP2612_DEADLINE_EXPIRED",
    "ERR_ERC20_APPROVAL_EXTENSION_FORMAT",
    "ERR_ERC20_APPROVAL_FROM_MISMATCH",
    "ERR_ERC20_APPROVAL_ASSET_MISMATCH",
    "ERR_ERC20_APPROVAL_SPENDER_NOT_PERMIT2",
    "ERR_ERC20_APPROVAL_TX_FAILED",
    "ERR_FAILED_TO_GET_NETWORK_CONFIG",
    "ERR_FAILED_TO_GET_ASSET_INFO",
    "ERR_FAILED_TO_VERIFY_SIGNATURE",
    "TRANSFER_WITH_AUTHORIZATION_VRS_ABI",
    "TRANSFER_WITH_AUTHORIZATION_BYTES_ABI",
    "AUTHORIZATION_STATE_ABI",
    "BALANCE_OF_ABI",
    "ERC20_ALLOWANCE_ABI",
    "ERC20_APPROVE_ABI",
    "EIP2612_PERMIT_TYPES",
    "EIP2612_NONCES_ABI",
    "ERC20_APPROVE_GAS_LIMIT",
    "DEFAULT_MAX_FEE_PER_GAS",
    "DEFAULT_MAX_PRIORITY_FEE_PER_GAS",
    "IS_VALID_SIGNATURE_ABI",
    "PERMIT2_WITNESS_TYPES",
    "PERMIT2_ADDRESS",
    "PERMIT2_ADDRESSES",
    "X402_EXACT_PERMIT2_PROXY_ADDRESS",
    "X402_EXACT_PERMIT2_PROXY_ADDRESSES",
    "get_permit2_address",
    "get_x402_exact_permit2_proxy_address",
    "x402ExactPermit2ProxyABI",
    "AssetInfo",
    "NetworkConfig",
    # Types
    "ExactEIP3009Authorization",
    "ExactEIP3009Payload",
    "ExactPermit2Payload",
    "ExactEvmPayloadV1",
    "ExactEvmPayloadV2",
    "Permit2Authorization",
    "Permit2Witness",
    "TypedDataDomain",
    "TypedDataField",
    "TransactionReceipt",
    "ERC6492SignatureData",
    "AUTHORIZATION_TYPES",
    "DOMAIN_TYPES",
    "is_permit2_payload",
    # Signer protocols
    "ClientEvmSigner",
    "FacilitatorEvmSigner",
    # Signer implementations
    "EthAccountSigner",
    "FacilitatorWeb3Signer",
    # Utilities
    "get_evm_chain_id",
    "get_network_config",
    "get_asset_info",
    "is_valid_network",
    "create_nonce",
    "normalize_address",
    "is_valid_address",
    "parse_amount",
    "format_amount",
    "create_validity_window",
    "hex_to_bytes",
    "bytes_to_hex",
    "parse_money_to_decimal",
    # EIP-712
    "hash_typed_data",
    "hash_eip3009_authorization",
    "hash_struct",
    "hash_domain",
    "build_typed_data_for_signing",
    # ERC-6492
    "is_erc6492_signature",
    "parse_erc6492_signature",
    "is_eoa_signature",
    "has_deployment_info",
    # Verification
    "verify_eoa_signature",
    "verify_eip1271_signature",
    "verify_universal_signature",
]
